services:
  libserver:
    image: nginx:alpine@sha256:f46cb72c7df02710e693e863a983ac42f6a9579058a59a35f1ae36c9958e4ce0
    restart: on-failure
    ports:
      - "18082:80"
    volumes:
      - "..:/srv"
      - ./nginx.conf:/etc/nginx/conf.d/default.conf