services:
  libserver:
    image: nginx:alpine@sha256:9c5e088b4dababb9fb4a2523bdddf74fd32c0ed748226ac71094ba599681a33d
    restart: on-failure
    ports:
      - "18082:80"
    volumes:
      - "..:/srv"
      - ./nginx.conf:/etc/nginx/conf.d/default.conf