FROM node:24.15.0-slim@sha256:24dc26ef1e3c3690f27ebc4136c9c186c3133b25563ae4d7f0692e4d1fe5db0e AS builder
ARG NODE_ENV=production
ARG SERVICE
WORKDIR /app
RUN chown -R node:node /app

USER root

RUN apt-get update \
  && apt-get install -y --no-install-recommends  python3 make g++ \
  && ln -sf python3 /usr/bin/python \
  && corepack enable \
  && corepack prepare pnpm@10.30.2 --activate

USER node

COPY --chown=node:node package*.json pnpm-lock.yaml pnpm-workspace.yaml lerna.json ./
COPY --chown=node:node .husky ./.husky
COPY --chown=node:node packages ./packages
COPY --chown=node:node servers ./servers
COPY --chown=node:node samples ./samples
RUN HUSKY=0 pnpm install --frozen-lockfile

FROM node:24.15.0-slim@sha256:24dc26ef1e3c3690f27ebc4136c9c186c3133b25563ae4d7f0692e4d1fe5db0e
ARG SERVICE
WORKDIR /app
RUN corepack enable \
  && corepack prepare pnpm@10.30.2 --activate
COPY --chown=node:node --from=builder /app .
USER node
WORKDIR "/app/servers/$SERVICE"

EXPOSE 3000
ENTRYPOINT ["pnpm", "start"]
