FROM node:22.20.0-slim@sha256:c407baf6e71f4127777b0b660b162e3c88c1974067b1be9f1f962709ea817d59 AS builder
ARG NODE_ENV=production
ARG SERVICE
WORKDIR /app
RUN chown -R node:node /app

USER root

RUN apt-get update \
  && apt-get install -y --no-install-recommends  python3 make g++ \
  && ln -sf python3 /usr/bin/python

USER node

COPY --chown=node:node package*.json yarn.lock lerna.json ./
COPY --chown=node:node packages ./packages
COPY --chown=node:node servers ./servers
RUN yarn --production --pure-lockfile

FROM node:22.20.0-slim@sha256:c407baf6e71f4127777b0b660b162e3c88c1974067b1be9f1f962709ea817d59
WORKDIR /app
COPY --chown=node:node --from=builder /app .
WORKDIR "/app/servers/$SERVICE"

EXPOSE 3000
ENTRYPOINT ["yarn", "start"]
