name: Vulnerability Audit
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  NODE_VERSION: '24'
jobs:
  build:
    name: Vulnerability Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Enable Corepack
        run: corepack enable
      - name: Get pnpm store path
        id: pnpm-store-path
        run: echo "dir=$(pnpm store path)" >> "$GITHUB_OUTPUT"
      - name: Cache node modules
        id: pnpm-cache # use this to check for `cache-hit` (`steps.pnpm-cache.outputs.cache-hit != 'true'`)
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ${{ steps.pnpm-store-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install --prod --frozen-lockfile
      - name: Run Vulnerability Audit
        run: pnpm audit --prod --no-optional --audit-level high
